# Generated by Django 4.1 on 2023-01-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=128)),
                ('event_date', models.DateField(max_length=128)),
                ('event_description', models.CharField(max_length=628)),
                ('event_image', models.ImageField(blank=True, upload_to='event_images')),
            ],
        ),
    ]
