# Generated by Django 4.1 on 2023-01-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odbc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(max_length=128),
        ),
    ]
