# Generated by Django 4.1 on 2023-01-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odbc', '0002_alter_events_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, default='../media/announcements/event_images/default.jpg', upload_to='announcements/event_images'),
        ),
    ]
