# Generated by Django 4.1 on 2023-01-17 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('odbc', '0003_alter_events_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(max_length=128),
        ),
    ]
