# Generated by Django 4.1 on 2023-01-17 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odbc', '0004_events_event_time_alter_events_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.date.today, max_length=128),
        ),
    ]
