# Generated by Django 4.1 on 2023-01-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odbc', '0005_alter_events_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=128)),
                ('work_summary', models.CharField(max_length=128)),
                ('work_description', models.CharField(max_length=628)),
                ('work_image', models.ImageField(blank=True, default='../media/work_blog/work_images/default.jpg', upload_to='work_blog/work_images')),
            ],
        ),
    ]
