# Generated by Django 4.1 on 2023-06-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odbc', '0006_work_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='work_blog',
        ),
    ]
